from __future__ import annotations

from pathlib import Path

from xhx_agent.repo_intel.scanner import ProjectScan


def render_xhx_md(scan: ProjectScan) -> str:
    languages = ", ".join(scan.detected_languages) or "unknown"
    node_scripts = scan.node.get("scripts", {})
    script_lines = "\n".join(f"- npm run {name}" for name in sorted(node_scripts)) or "- none detected"
    verification: list[str] = []
    if scan.python.get("tests_dir") or scan.python.get("pytest_ini"):
        verification.append("- uv run pytest" if scan.python.get("pyproject") else "- python -m pytest")
    if isinstance(node_scripts, dict):
        if "test" in node_scripts:
            verification.append("- npm test")
        if "typecheck" in node_scripts:
            verification.append("- npm run typecheck")
        if "build" in node_scripts:
            verification.append("- npm run build")
    verification_lines = "\n".join(verification) or "- no automatic verification detected"
    return f"""# XHX Project Map

## Project

- root: {scan.root}
- detected languages: {languages}
- file count: {scan.file_count}

## Structure

- Python: {scan.python}
- Node: package_json={scan.node.get("package_json")}, tsconfig={scan.node.get("tsconfig")}

## Scripts

{script_lines}

## Verification

{verification_lines}

## Notes

- Generated by `xhx init`.
"""


def write_xhx_md(workspace: Path, scan: ProjectScan) -> bool:
    path = workspace / "XHX.md"
    if path.exists():
        return False
    path.write_text(render_xhx_md(scan), encoding="utf-8")
    return True
